name: Codex Maintainer

on:
  push:
    paths:
      - 'news/**/*.md'
      - 'news/index.md'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  codex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Codex Action
        uses: openai/codex-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          prompt-path: prompt.md               # uzun kurallarını bu dosyaya koy
          file-globs: |
            news/**/*.md
            news/index.md
          extra-context-globs: |               # sadece OKU: şemayı referans alsın
            scripts/validate_news_schema.py
            domain_weights.yml
          output-report: codex_report.md       # köke rapor yazar
          commit-message: "chore(codex): normalize news markdown"
          fail-on-error: false                 # otomatik düzeltilemeyenler için run başarısız olmasın
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
